apiBaseUrl=http://localhost:4111
apiVersion=/api/v1

admin.username = admin
admin.password = admin
admin.token = Basic YWRtaW46YWRtaW4=

db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres

uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://frontend
browser = chrome
browserSize = 1920x1080