name: Run tests

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/**"

  workflow_dispatch:

jobs:
  run-tests:
    name: Set up services and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services
        run: bash infra/docker_compose/restart_nbank_with_update_images.sh

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw clean test -q
        env:
          APIBASEURL: http://localhost:80
          UIBASEURL: http://host.docker.internal